/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package euler1;

/**
 *
 * @author stastudents
 */
public class Euler2 {
    public static void main(String[] args) {
        /* Each new term in the Fibonacci sequence is generated by adding the
         * previous two terms. By started with 1 and 2, the first 10 terms will
         * be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
         * By considering the terms in the Fibonacci sequence whose values do
         * not exceed four million, find the sum of the even-valued terms.
         */
        
        // declare variables
        int num1 = 0;
        int num2 = 1;
        int temp = 1;
        int cap = 4000000;
        int even = 0;

        while(num2 < cap){
            temp = num2;
            num2 = num2 + num1;
            num1 = temp;
            if(temp%2==0){
                even+=temp;
            }
        }
        System.out.println(even);
    }   
    
    
}
